### ISSUE TITLE
[PE-D][Tester D] Bug: Invalid editStock command shows wrong error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-4/tp#219] opened 2022-10-29 04:23 UTC
Steps to reproduce:
1. Enter `editStock 2 c/-1` into the command box.
2. Press 'Enter' to execute the command.

Expected: Correct error message saying no negative values should be provided.

Actual: Error message saying "At least one field to edit must be provided."

![Screenshot 2022-10-28 at 5.03.45 PM.png](https://raw.githubusercontent.com/jeromepui/ped/main/files/b556695e-9643-473c-9424-55a7f8602610.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jeromepui/ped#9

**Comment by hauchongtang** [comment] 2022-10-29 17:17
Duplicate of #205

**Closed** 2022-10-29 17:17 UTC
